/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopBoosterIdRouteImport } from './routes/shop.$boosterId'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBoosterIdRoute = ShopBoosterIdRouteImport.update({
  id: '/$boosterId',
  path: '/$boosterId',
  getParentRoute: () => ShopRoute,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => InventoryRoute,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/shop/$boosterId': typeof ShopBoosterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/shop/$boosterId': typeof ShopBoosterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/shop/$boosterId': typeof ShopBoosterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/auth'
    | '/inventory'
    | '/shop'
    | '/card/$cardId'
    | '/inventory/$itemId'
    | '/shop/$boosterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/auth'
    | '/inventory'
    | '/shop'
    | '/card/$cardId'
    | '/inventory/$itemId'
    | '/shop/$boosterId'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/auth'
    | '/inventory'
    | '/shop'
    | '/card/$cardId'
    | '/inventory/$itemId'
    | '/shop/$boosterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  AuthRoute: typeof AuthRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  CardCardIdRoute: typeof CardCardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$boosterId': {
      id: '/shop/$boosterId'
      path: '/$boosterId'
      fullPath: '/shop/$boosterId'
      preLoaderRoute: typeof ShopBoosterIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InventoryRouteChildren {
  InventoryItemIdRoute: typeof InventoryItemIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemIdRoute: InventoryItemIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface ShopRouteChildren {
  ShopBoosterIdRoute: typeof ShopBoosterIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopBoosterIdRoute: ShopBoosterIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  AuthRoute: AuthRoute,
  InventoryRoute: InventoryRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  CardCardIdRoute: CardCardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
